// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Qemj8IjKyGsWDfq87D6KQuG3i9uFpHM',
    appId: '1:595245230167:web:93690f684df6a3073e1b12',
    messagingSenderId: '595245230167',
    projectId: 'homework-41803',
    authDomain: 'homework-41803.firebaseapp.com',
    storageBucket: 'homework-41803.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkH54FItyn4Th4vV0CMMhnMAkMIWqa_68',
    appId: '1:595245230167:android:d35c5bce57851fd23e1b12',
    messagingSenderId: '595245230167',
    projectId: 'homework-41803',
    storageBucket: 'homework-41803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeIArhOnIxDv7piSQJT0RAob3SeAsWzz0',
    appId: '1:595245230167:ios:d35078c865ad3ae43e1b12',
    messagingSenderId: '595245230167',
    projectId: 'homework-41803',
    storageBucket: 'homework-41803.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeIArhOnIxDv7piSQJT0RAob3SeAsWzz0',
    appId: '1:595245230167:ios:d35078c865ad3ae43e1b12',
    messagingSenderId: '595245230167',
    projectId: 'homework-41803',
    storageBucket: 'homework-41803.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Qemj8IjKyGsWDfq87D6KQuG3i9uFpHM',
    appId: '1:595245230167:web:3719498cc326dea03e1b12',
    messagingSenderId: '595245230167',
    projectId: 'homework-41803',
    authDomain: 'homework-41803.firebaseapp.com',
    storageBucket: 'homework-41803.firebasestorage.app',
  );
}
